<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>researcher-analysis-service-7ee882b9-4273-45ec-9928-a42501ff4f15</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ResearcherAnalysis.Contracts/ResearcherAnalysis.Contracts.csproj" />
  </ItemGroup>
</Project>
