<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>84125b1e-2b71-4e7f-bebc-914f83674f79</UserSecretsId>
    <SerenityUsings>false</SerenityUsings>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptNoEmitOnError>false</TypeScriptNoEmitOnError>
    <GenerateComputedBuildStaticWebAssetsDependsOn>RunTSBuild;$(GenerateComputedBuildStaticWebAssetsDependsOn)</GenerateComputedBuildStaticWebAssetsDependsOn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator.Runner.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Serenity.Assets" Version="10.3.7" />
    <PackageReference Include="Serenity.Corelib" Version="10.3.7" />
    <PackageReference Include="Serenity.Extensions" Version="10.3.7" />
    <PackageReference Include="Serenity.Net.Web" Version="10.3.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="academicsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\AcademicPerformance\Background\" />
    <Compile Remove="AcademicCollectorDemo.Tests\**\*" />
    <Content Remove="AcademicCollectorDemo.Tests\**\*" />
    <None Remove="AcademicCollectorDemo.Tests\**\*" />
  </ItemGroup>

  <Target Name="NpmInstall" Condition="!Exists('node_modules\@serenity-is\tsbuild\package.json')">
    <Message Text="Installing NPM packages for $(ProjectName)..." Importance="high" />
    <Exec Command="npm install" />
  </Target>

  <Target Name="RunTSBuild" DependsOnTargets="RestoreNodeTypes;NpmInstall" BeforeTargets="ResolveProjectStaticWebAssets" AfterTargets="ResolveProjectReferences" Condition="'$(SkipTSBuild)' != 'true'">
    <Message Text="Executing TypeScript compiler for $(ProjectName)..." Importance="high" />
    <Exec Command="node ./tsbuild.js" />
    <ItemGroup>
      <Content Include="wwwroot\esm\**\*.js;wwwroot\esm\**\*.css;wwwroot\esm\**\*.map" Exclude="@(Content)" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    </ItemGroup>
  </Target>

</Project>
