@host = http://localhost:5000
@orcid = 0000-0003-2812-9917

### Uygulamanın çalıştığını kontrol et
GET {{host}}/
Accept: application/json

### ORCID ile akademisyen verisini topla
POST {{host}}/Services/AcademicPerformance/Researcher/Collect
Content-Type: application/json

{
  "Identifiers": [
    "{{orcid}}"
  ]
}
